env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  no-console: "off"
  max-classes-per-file: [2, 5]
  no-underscore-dangle: "off"
  no-plusplus: [error, {allowForLoopAfterthoughts: true}]
  max-len: "off"
  no-restricted-syntax: "off"
  no-unused-expressions: "off"
  no-param-reassign: "off"

