env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  no-console: 0
  max-classes-per-file: [2, 5]
  no-underscore-dangle: "off"
  no-plusplus: [error, {allowForLoopAfterthoughts: true}]

